package gui;

import exceptions.IdInvalidException;
import model.Store;
import model.Customer;
import model.Gender;
import exceptions.ObjectNotFoundException;
import exceptions.StringVoidException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Marlon E. Zambrano Z.
 */
public class CustomerUI extends javax.swing.JInternalFrame {

    private Store store;
    private Customer customerRegistered;

    /**
     * Creates new form GestionarClientes
     */
    public CustomerUI(Store store) {
        this.store = store;
        initComponents();
        HandlerFindCustomer handlerFind = new HandlerFindCustomer();
        btnCancel.doClick();
        btnSave.addActionListener(new HandlerSignInCustomer());
        btnSearch.addActionListener(handlerFind);
        txfIdentification.addActionListener(handlerFind);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfIdentification = new javax.swing.JTextField();
        txfNames = new javax.swing.JTextField();
        txfLastnames = new javax.swing.JTextField();
        cbxGender = new JComboBox<Gender>(Gender.values());
        cbxGender.setSelectedItem(null);
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        ftxPhone = new javax.swing.JFormattedTextField();
        ftxEmail = new javax.swing.JFormattedTextField();

        labManagementPurchase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labManagementPurchase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labManagementPurchase.setText("Gestionar Clientes");

        labIdentification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labIdentification.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labIdentification.setText("Identificacion :");

        labNames.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labNames.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNames.setText("Nombre(s) :");

        labLastnames.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labLastnames.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labLastnames.setText("Apellido(s) :");

        labGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labGender.setText("Genero :");

        labPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPhone.setText("Telefono :");

        labEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmail.setText("Correo :");

        btnSave.setText("Guardar");

        btnCancel.setText("Cancelar");

        btnSearch.setText("...");

        ftxPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        try {
            ftxEmail.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***********************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labManagementPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labIdentification, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(labNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labLastnames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(labGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txfIdentification)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch))
                            .addComponent(txfNames, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(txfLastnames)
                            .addComponent(cbxGender, 0, 302, Short.MAX_VALUE)
                            .addComponent(ftxPhone)
                            .addComponent(ftxEmail))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labManagementPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNames, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labLastnames, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfLastnames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPhone)
                    .addComponent(ftxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Gender> cbxGender;
    private javax.swing.JFormattedTextField ftxEmail;
    private javax.swing.JFormattedTextField ftxPhone;
    private final javax.swing.JLabel labEmail = new javax.swing.JLabel();
    private final javax.swing.JLabel labGender = new javax.swing.JLabel();
    private final javax.swing.JLabel labIdentification = new javax.swing.JLabel();
    private final javax.swing.JLabel labLastnames = new javax.swing.JLabel();
    private final javax.swing.JLabel labManagementPurchase = new javax.swing.JLabel();
    private final javax.swing.JLabel labNames = new javax.swing.JLabel();
    private final javax.swing.JLabel labPhone = new javax.swing.JLabel();
    private javax.swing.JTextField txfIdentification;
    private javax.swing.JTextField txfLastnames;
    private javax.swing.JTextField txfNames;
    // End of variables declaration//GEN-END:variables

    private void makeDeleteFields() {
        txfIdentification.setText("");
        txfNames.setText("");
        txfLastnames.setText("");
        ftxPhone.setText("");
        ftxEmail.setText("");
        cbxGender.setSelectedItem(null);
        cbxGender.updateUI();

    }

    public class HandlerDeleteFields implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            makeDeleteFields();
        }

    }

    public class HandlerSignInCustomer implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                long phone = Long.parseLong(ftxPhone.getText());
                String email = (ftxEmail.getValue().toString()).trim();
                long id = Long.parseLong(txfIdentification.getText());
                String names = txfNames.getText().trim();
                String lastNames = txfLastnames.getText().trim();
                Gender gender = (Gender) cbxGender.getSelectedItem();
                if (customerRegistered == null) {
                    customerRegistered = new Customer(phone, email, id, names, lastNames, gender);
                    store.addNewCustomer(customerRegistered);  
                } else {
                    customerRegistered = store.findCustomerByID(id);
                    customerRegistered.setNames(names );
                    customerRegistered.setLastNames(lastNames );
                    customerRegistered.setEmail(email );
                    customerRegistered.setGender(gender );
                    customerRegistered.setPhone(phone );
                    makeDeleteFields();
                }
            } catch (StringVoidException | IdInvalidException ex) {
                JOptionPane.showMessageDialog(CustomerUI.this, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(CustomerUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public class HandlerFindCustomer implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                long id = Long.parseLong(txfIdentification.getText());
                Customer customerFound = store.findCustomerByID(id);
                txfNames.setText(customerFound.getNames());
                txfLastnames.setText(customerFound.getLastNames());
                cbxGender.setSelectedItem(customerFound.getGender());
                ftxPhone.setText(String.valueOf(customerFound.getPhone()));
                ftxEmail.setText(customerFound.getEmail());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(CustomerUI.this, ex.getMessage());
            } catch (ObjectNotFoundException ex) {
                int option = JOptionPane.showConfirmDialog(CustomerUI.this, "No se encuentra un cliente "
                        + "con el numero de identificacion ingresado\n �Desea "
                        + "registrar el cliente ?", "Gestionar cliente",
                        JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    txfNames.requestFocus();
                }
            }
        }
    }

}
