/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.Store;
import model.Product;
import model.TypeProduct;
import exceptions.ObjectNotFoundException;
import exceptions.StringVoidException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import model.CodeInvalidException;

/**
 *
 * @author Marlon E. Zambrano Z.
 */
public class ProductsUI extends javax.swing.JInternalFrame {

    private Store store;
    private Product productRegistered;

    /**
     * Creates new form GestionarProductos
     */
    public ProductsUI(Store store) {
        this.store = store;
        initComponents();
        //Agregando eventos        
        HandlerFindProduct handlerFind = new HandlerFindProduct();
        jBBuscar.addActionListener(handlerFind);
        jTFCodigo.addActionListener(handlerFind);
        jBGuardar.addActionListener(new HandlerSaveProduct());
        jBCancelar.addActionListener(new HandlerDeleteFields());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFCodigo = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jFTFCosto = new javax.swing.JFormattedTextField();
        jCBTipoDeProducto = new javax.swing.JComboBox<>();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jLGestionarProductos = new javax.swing.JLabel();
        jLTipoDeProducto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLCodigo.setText("Codigo :");

        jLNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre.setText("Nombre :");

        jLCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLCosto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLCosto.setText("Costo :");

        jFTFCosto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jCBTipoDeProducto.setModel(new ComboBoxProducts());

        jBGuardar.setText("Guardar");

        jBCancelar.setText("Cancelar");

        jBBuscar.setText("...");

        jLGestionarProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLGestionarProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLGestionarProductos.setText("Gestionar Productos");

        jLTipoDeProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLTipoDeProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLTipoDeProducto.setText("Tipo de Producto :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLGestionarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBGuardar)
                .addGap(59, 59, 59)
                .addComponent(jBCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLTipoDeProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNombre)
                            .addComponent(jFTFCosto)
                            .addComponent(jCBTipoDeProducto, 0, 230, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLGestionarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuscar)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCodigo))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCosto)
                    .addComponent(jFTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<TypeProduct> jCBTipoDeProducto;
    private javax.swing.JFormattedTextField jFTFCosto;
    private final javax.swing.JLabel jLCodigo = new javax.swing.JLabel();
    private final javax.swing.JLabel jLCosto = new javax.swing.JLabel();
    private javax.swing.JLabel jLGestionarProductos;
    private final javax.swing.JLabel jLNombre = new javax.swing.JLabel();
    private javax.swing.JLabel jLTipoDeProducto;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables

    public class HandlerDeleteFields implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            jTFCodigo.setText("");
            jTFNombre.setText("");
            jFTFCosto.setText("");
            jCBTipoDeProducto.setSelectedItem(null);
            jCBTipoDeProducto.updateUI();

        }
    }

    public class HandlerFindProduct implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            try {
                long code = Long.parseLong(jTFCodigo.getText());
                Product productFound = store.findProductByCode(code);
                jTFNombre.setText(productFound.getName());
                jFTFCosto.setText(productFound.getCost().toString());
                jCBTipoDeProducto.setSelectedItem(productFound.getTypeProduct());
            } catch (ObjectNotFoundException ex) {
                int option = JOptionPane.showConfirmDialog(ProductsUI.this,
                        ex.getMessage() + "\nyou want to register it?",
                        "Gestionar Productos", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    jTFNombre.requestFocus();
                }
            } catch (CodeInvalidException ex) {
                JOptionPane.showMessageDialog(ProductsUI.this, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(ProductsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public class HandlerSaveProduct implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                long code = Long.parseLong(jTFCodigo.getText());
                if (productRegistered == null) {
                    String name = jTFNombre.getText();
                    Double cost = Double.parseDouble((String.valueOf(jFTFCosto.getValue()).trim()));
                    TypeProduct typeProduct = (TypeProduct) jCBTipoDeProducto.getSelectedItem();
                    productRegistered = new Product(code, name, cost, typeProduct);
                    store.addNewProduct(productRegistered);
                } else {
                    productRegistered = store.findProductByCode(code);
                    productRegistered.setName(jTFNombre.getText());
                    productRegistered.setCost(Double.parseDouble(jFTFCosto.getText()));
                    productRegistered.setTypeProduct((TypeProduct) jCBTipoDeProducto.getSelectedItem());
                }
            } catch (StringVoidException | CodeInvalidException ex) {
                JOptionPane.showMessageDialog(ProductsUI.this, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(ProductsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public class ComboBoxProducts implements ComboBoxModel<TypeProduct> {

        public TypeProduct selected;

        @Override
        public TypeProduct getSelectedItem() {
            return this.selected;
        }

        @Override
        public void setSelectedItem(Object item) {
            this.selected = (TypeProduct) item;
        }

        @Override
        public int getSize() {
            return store.getTypeProducts().size();
        }

        @Override
        public TypeProduct getElementAt(int index) {
            return store.getTypeProducts().get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }

    }
}
