/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.Store;
import model.Product;
import model.TypeProduct;
import exceptions.ObjectNotFoundException;
import exceptions.StringVoidException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import model.CodeInvalidException;

/**
 *
 * @author Marlon E. Zambrano Z.
 */
public class ProductsUI extends javax.swing.JInternalFrame {

    private Store store;
    private Product productRegistered;

    /**
     * Creates new form GestionarProductos
     */
    public ProductsUI(Store store) {
        this.store = store;
        initComponents();
        //Agregando eventos        
        HandlerFindProduct handlerFind = new HandlerFindProduct();
        btnSearch.addActionListener(handlerFind);
        txfCode.addActionListener(handlerFind);
        btnSave.addActionListener(new HandlerSaveProduct());
        btnCancel.addActionListener(new HandlerDeleteFields());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfCode = new javax.swing.JTextField();
        txfName = new javax.swing.JTextField();
        ftxCost = new javax.swing.JFormattedTextField();
        cbxTypeProduct = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        labManagementProducts = new javax.swing.JLabel();
        labTypeProduct = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        labCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCode.setText("Codigo :");

        labName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labName.setText("Nombre :");

        labCost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labCost.setText("Costo :");

        ftxCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        cbxTypeProduct.setModel(new ComboBoxProducts());

        btnSave.setText("Guardar");

        btnCancel.setText("Cancelar");

        btnSearch.setText("...");

        labManagementProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labManagementProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labManagementProducts.setText("Gestionar Productos");

        labTypeProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labTypeProduct.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labTypeProduct.setText("Tipo de Producto :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labManagementProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(59, 59, 59)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(labCode, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(labTypeProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labCost, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(txfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfName)
                            .addComponent(ftxCost)
                            .addComponent(cbxTypeProduct, 0, 230, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labManagementProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txfCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCode))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labName)
                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCost)
                    .addComponent(ftxCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTypeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTypeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<TypeProduct> cbxTypeProduct;
    private javax.swing.JFormattedTextField ftxCost;
    private final javax.swing.JLabel labCode = new javax.swing.JLabel();
    private final javax.swing.JLabel labCost = new javax.swing.JLabel();
    private javax.swing.JLabel labManagementProducts;
    private final javax.swing.JLabel labName = new javax.swing.JLabel();
    private javax.swing.JLabel labTypeProduct;
    private javax.swing.JTextField txfCode;
    private javax.swing.JTextField txfName;
    // End of variables declaration//GEN-END:variables

    public class HandlerDeleteFields implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            txfCode.setText("");
            txfName.setText("");
            ftxCost.setText("");
            cbxTypeProduct.setSelectedItem(null);
            cbxTypeProduct.updateUI();

        }
    }

    public class HandlerFindProduct implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            try {
                long code = Long.parseLong(txfCode.getText());
                Product productFound = store.findProductByCode(code);
                txfName.setText(productFound.getName());
                ftxCost.setText(productFound.getCost().toString());
                cbxTypeProduct.setSelectedItem(productFound.getTypeProduct());
            } catch (ObjectNotFoundException ex) {
                int option = JOptionPane.showConfirmDialog(ProductsUI.this,
                        ex.getMessage() + "\nyou want to register it?",
                        "Gestionar Productos", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    txfName.requestFocus();
                }
            } catch (CodeInvalidException ex) {
                JOptionPane.showMessageDialog(ProductsUI.this, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(ProductsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public class HandlerSaveProduct implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                long code = Long.parseLong(txfCode.getText());
                if (productRegistered == null) {
                    String name = txfName.getText();
                    Double cost = Double.parseDouble((String.valueOf(ftxCost.getValue()).trim()));
                    TypeProduct typeProduct = (TypeProduct) cbxTypeProduct.getSelectedItem();
                    productRegistered = new Product(code, name, cost, typeProduct);
                    store.addNewProduct(productRegistered);
                } else {
                    productRegistered = store.findProductByCode(code);
                    productRegistered.setName(txfName.getText());
                    productRegistered.setCost(Double.parseDouble(ftxCost.getText()));
                    productRegistered.setTypeProduct((TypeProduct) cbxTypeProduct.getSelectedItem());
                }
            } catch (StringVoidException | CodeInvalidException ex) {
                JOptionPane.showMessageDialog(ProductsUI.this, ex.getMessage());
            } catch (Exception ex) {
                Logger.getLogger(ProductsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public class ComboBoxProducts implements ComboBoxModel<TypeProduct> {

        public TypeProduct selected;

        @Override
        public TypeProduct getSelectedItem() {
            return this.selected;
        }

        @Override
        public void setSelectedItem(Object item) {
            this.selected = (TypeProduct) item;
        }

        @Override
        public int getSize() {
            return store.getTypeProducts().size();
        }

        @Override
        public TypeProduct getElementAt(int index) {
            return store.getTypeProducts().get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }

    }
}
